# Generated by Django 3.1 on 2020-08-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200819_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents', models.CharField(max_length=3)),
                ('me', models.TextField()),
                ('brother', models.DateTimeField(auto_now_add=True)),
                ('sister', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
